### ISSUE TITLE
Allow any diagonal value for slave and dirichlet DoF

### ISSUE THREAD

**Issue by fmonteghetti** [jorgensd/dolfinx_mpc#3] opened 2021-05-14 20:42 UTC
Thank you for this excellent code, which makes dolfinx even more appealing!

I open this issue to share a patch that will be useful to anyone interested in solving generalized eigenvalue problems using matrices assembled with dolfinx_mpc. I can create a pull request if you think this is worth it.

Currently, dolfinx_mpc uses a diagonal value equal to 1 for slave dof associated with multi-point constraints as well as dof associated with Dirichlet boundary conditions. This can be a limitation when solving a generalized eigenvalue problem 

A * x = lambda * B * x 

where both A and B are asssembled using dolfinx_mpc. Indeed, the current implementation will lead to spurious eigenfunctions (localized at slave or Dirichlet dof) associated with lambda = 1. 

When assembling using dolfinx the diagonal value is an input argument, which enables to use different values for A and B. This is useful since the spurious eigenvalues are now at lambda=diagval_A/diagval_B, i.e. they can be placed far from the region of interest.

Only trivial changes are required to enable a user-defined diagonal value in dolfinx_mpc. I have been successfully using the attached patch, which modifies:
    /cpp/assembly.cpp::_assemble_matrix
    /python/dolfinx_mpc/assemble_matrix.py::assemble_matrix_cpp
    /python/dolfinx_mpc/assemble_matrix.py::assemble_matrix
    /python/dolfinx_mpc/assemble_matrix.py::add_diagonal.

Beware that this patch relies on a somewhat older version of dolfinx_mpc, specifically:
commit 58855754d7b36bbc8e65c2e5f288a9fb4473fd6
Merge: dfe48c5 4c9b04c
Author: J<C3><B8>rgen Dokken <jsd55@cam.ac.uk>
Date:   Fri Mar 12 14:28:52 2021 +0000

[diagval.patch.txt](https://github.com/jorgensd/dolfinx_mpc/files/6481109/diagval.patch.txt)

**Comment by jorgensd** [comment] 2021-05-15 10:45
I can add this patch, if you give me a example code that I can add to the demos to illustrate the behaviour.

**Comment by fmonteghetti** [comment] 2021-05-17 08:17
[demo_periodic_gep.zip](https://github.com/jorgensd/dolfinx_mpc/files/6492282/demo_periodic_gep.zip)

You will find attached a demo adapted from demo_periodic.py. It computes the eigenvalues of the Laplacian on a square with a mix of Dirichlet and periodic boundary conditions. The computed eigenvalues are printed alongside the exact ones. 

For reference, below are the results I obtain on my local machine.

The demo uses the diagonal values diagval_A = 1e2 and diagval_B = 1e-2, which leads to a correct calculation of the first eigenvalues:
    Computed eigenvalues:
     [  9.87+0.j  39.53+0.j  49.46+0.j  49.46+0.j  79.27+0.j  79.27+0.j
    89.09+0.j 129.09+0.j 129.09+0.j 158.75+0.j 168.82+0.j]
    Exact eigenvalues:
     [  9.87  39.48  49.35  78.96  88.83 128.3  157.91 167.78 197.39].

By constrast, choosing the same diagonal values for A and B leads to a spurious eigenvalue at 1. For example, choosing diagval_A = 1 and diagval_B = 1 (the default behavior) leads to:
    Computed eigenvalues:
     [ 1.  +0.j  1.  +0.j  1.  +0.j  1.  +0.j  1.  +0.j  1.  +0.j  9.87+0.j
 39.53+0.j 49.46+0.j 49.46+0.j 79.27+0.j].

Similarly, choosing diagval_A = 1e2 and diagval_B = 1e2 yields:
    Computed eigenvalues:
     [ 1.  +0.j  1.  +0.j  1.  +0.j  1.  +0.j  1.  +0.j  1.  +0.j  9.87+0.j
 39.53+0.j 49.46+0.j 49.46+0.j 79.27+0.j].

**Comment by jorgensd** [comment] 2021-05-17 08:55
I'll have a look at this sometime this or next week

**Comment by jorgensd** [comment] 2021-06-09 14:13
@fmonteghetti Sorry for not getting to this yet. Im going to try to get this into my work next week

**Comment by fmonteghetti** [comment] 2021-06-09 14:15
> @fmonteghetti Sorry for not getting to this yet. Im going to try to get this into my work next week
No worries! Tell me if there is anything I can do to help.

**Comment by jorgensd** [comment] 2021-06-22 08:20
Patch should be added later today (Just implemented it, but need to wait for some other fixes to go through my CI).

**Comment by jorgensd** [comment] 2021-06-22 08:22
@fmonteghetti Could I get your full name, such that I can add it to the header of the demo with a copyright notice?

**Comment by jorgensd** [comment] 2021-06-22 10:18
@fmonteghetti Implementation of the `diagvalue` argument is in: https://github.com/jorgensd/dolfinx_mpc/compare/dokken/dof-perms-outside-kernel and will be merged in ~one hour. I've slightly rewritten your demo (updating docs). I've also made the demo work in parallel (previously throwing PETSc errors).

I observe that we get a few extra eigenvalues when running in parallel, is that expected? It would be great if you could test the new code and get back to me

**Comment by fmonteghetti** [comment] 2021-06-24 12:45
> @fmonteghetti Could I get your full name, such that I can add it to the header of the demo with a copyright notice?

Florian Monteghetti.

> @fmonteghetti Implementation of the `diagvalue` argument is in: https://github.com/jorgensd/dolfinx_mpc/compare/dokken/dof-perms-outside-kernel and will be merged in ~one hour. I've slightly rewritten your demo (updating docs). I've also made the demo work in parallel (previously throwing PETSc errors).

Thanks! I can't give you feedback for now, since I cannot compile the master branch from my usual docker container. Here are some of the errors I get (after git clone in an empty folder):
/root/dolfinx_mpc/cpp/SlipConstraint.cpp:105:23: error: 'view' is not a member of 'xt'; did you mean 'xview'?
/root/dolfinx_mpc/dolfinx_mpc/cpp/MultiPointConstraint.h:311:34: error: 'dolfinx::graph::scotch' has not been declared
/root/dolfinx_mpc/dolfinx_mpc/cpp/MultiPointConstraint.h:152:25: error: 'xtl' has not been declared
I'll report back if I can fix this.

> I observe that we get a few extra eigenvalues when running in parallel, is that expected? It would be great if you could test the new code and get back to me

I have never run in parallel, so I've never seen that behavior. I'll test it as soon as I can compile it.

**Comment by jorgensd** [comment] 2021-06-24 15:55
@fmonteghetti  It might be that the latest changes to dolfinx (as of today) has broken something. I will have a look later today or tomorrow.

**Comment by jorgensd** [comment] 2021-06-24 16:04
@fmonteghetti  I cannot reproduce your build issues locally?
What commands exactly did you use to build the docker container?
Have you pulled the latest `dolfinx/dev-env`?

**Comment by fmonteghetti** [comment] 2021-06-25 17:15
> @fmonteghetti I cannot reproduce your build issues locally?
> What commands exactly did you use to build the docker container?
> Have you pulled the latest `dolfinx/dev-env`?

You're right, my container was getting old. Downloading a new one fixed the issue! 

I have run demo_periodic_gep.py in both serial and parallel, below are the computed eigenvalues. 

=== Eigenvalues computed with 'demo_periodic_gep.py' from master branch
python3 demo_periodic_gep.py
 [  9.87+0.j  39.53+0.j  49.46+0.j  49.46+0.j  79.27+0.j  79.27+0.j
  89.09+0.j 129.09+0.j 129.09+0.j 158.75+0.j 168.82+0.j]
mpirun -n 4 python3 demo_periodic_gep.py
 [  9.87+0.j  39.53+0.j  49.46+0.j  49.46+0.j  79.27+0.j  79.27+0.j
  89.09+0.j 129.09+0.j 158.75+0.j 168.82+0.j]

As you mentioned, the second mode associated with lambda = 129 gets missed when running in parallel. This seems to be an oddity in the eigenvalue solver, since slightly increasing the tolerance to 1e-7 fixes the problem. 

Using the patch [demo_periodic_gep-patch.txt](https://github.com/jorgensd/dolfinx_mpc/files/6717779/demo_periodic_gep-patch.txt), the missing eigenvalues are back, see below.

=== Eigenvalues computed with patched 'demo_periodic_gep.py'
python3 demo_periodic_gep.py
 [  9.87+0.j  39.53+0.j  49.46+0.j  49.46+0.j  79.27+0.j  79.27+0.j
  89.09+0.j 129.09+0.j 129.09+0.j 158.75+0.j 168.82+0.j]
mpirun -n 4 python3 demo_periodic_gep.py 
 [  9.87+0.j  39.53+0.j  49.46+0.j  49.46+0.j  79.27+0.j  79.27+0.j
  89.09+0.j 129.09+0.j 129.09+0.j 158.75+0.j 168.82+0.j]

**Comment by jorgensd** [comment] 2021-06-25 17:36
I'll do this patch once Im back from vacation (in 10 days)

**Closed** 2022-02-08 17:37 UTC
